### ISSUE TITLE
You didn't add me to the licence area!

### ISSUE THREAD

**Issue by joecooldoo** [joecooldoo/Text-Based_Snap#1]
^^^^^^^^

**Comment by WarpedWartWars** [comment]
Fine, I'll add you. ~~That is, if I have write access.~~

**Comment by WarpedWartWars** [comment]
https://github.com/WarpedWartWars/Text-Based_Snap_for_joecooldoo/commit/9f99ef8d37fde00b42ff464a10bb7e43adeedcf6

You happy?

BTW I'm writing this on BlueStacks, an Android emulator.

**Comment by WarpedWartWars** [comment]
Can I close this now?
