### ISSUE TITLE
@joecooldoo Can you accept this?

### ISSUE THREAD

**Issue by WarpedWartWars** [joecooldoo/Text-Based_Snap#2]
![Screenshot (212)](https://user-images.githubusercontent.com/91039320/139958276-6dacc06a-40cc-4760-8966-85505c4d6cb5.png)
(that's a screenshot)

@joecooldoo

**Comment by joecooldoo** [comment]
I dont know where to find it.

**Comment by WarpedWartWars** [comment]
Could you tell me when you are ready?

**Comment by WarpedWartWars** [comment]
I re-transferred it.

**Comment by WarpedWartWars** [comment]
I'll assume you're ready.

...

@joecooldoo

**Comment by WarpedWartWars** [comment]
@joecooldoo

**Comment by WarpedWartWars** [comment]
@joecooldoo

**Comment by joecooldoo** [comment]
I'm not on Github often, usually I'm on to contribute help screens for Snap<i>!</i>. Tell me on the Snap<i>!</i> forums, as I'm on there more than here.

**Comment by WarpedWartWars** [comment]
Ok.

**Comment by WarpedWartWars** [comment]
I was going to close it myself, actually.
